services:
  redeemer:
    build: .
    volumes:
      - ./players.txt:/players.txt:ro
      - ./redeemer.db:/redeemer.db
    environment:
      PLAYER_FILE: /players.txt
      DB_PATH: /redeemer.db
    restart: unless-stopped
